# Generated by Django 2.1.2 on 2018-10-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_pwd', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_birth', models.IntegerField()),
                ('user_gender', models.CharField(max_length=5)),
                ('user_email', models.CharField(max_length=40)),
                ('user_phone', models.CharField(max_length=13)),
                ('c_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
